version: '3.7'

services:
  dashboard:
    image: getumbrel/dashboard
    build:
      context: packages/dashboard
      dockerfile: Dockerfile.dev
    volumes:
      - ${PWD}/packages/dashboard:/app
  manager:
    image: getumbrel/manager
    build:
      context: packages/manager
      dockerfile: Dockerfile.dev
    volumes:
      - ${PWD}/packages/manager:/app
