name: Create release on tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: docker buildx create --use
      - run: npm ci
      - run: npm run build
      # TODO Clean this up into a release script
      - run: cd build && mv umbreld-amd64 umbreld && tar -czvf umbreld-${{ github.ref_name }}-amd64.tar.gz umbreld && rm umbreld
      - run: cd build && mv umbreld-arm64 umbreld && tar -czvf umbreld-${{ github.ref_name }}-arm64.tar.gz umbreld && rm umbreld
      - run: cd ../ && git archive --format=tar.gz --output server/build/umbrel-${{ github.ref_name }}.tar.gz --prefix=umbrel-${{ github.ref_name }}/ ${{ github.ref_name }}
      - run: sha256sum build/* > build/SHA256SUMS
      - run: npx opentimestamps stamp build/SHA256SUMS || true # Don't fail the release if timestamping fails
      # TODO Generate release notes
      - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          draft: true
          name: umbrelOS ${{ github.ref_name }}
          files: server/build/*